---
output: pdf_document
---

```{r global_options, echo=FALSE, message=FALSE, warning=FALSE,include=FALSE, results='hide', fig.width=6, fig.height=4}
# preparation
rm(list = ls())
setwd("/Users/wanghanlin/Desktop/final project")
knitr::opts_chunk$set(
  fig.width=8, fig.height=8,
  echo=FALSE, warning=FALSE, message=FALSE
  )
# loading the font
library(extrafont)
font_import(
  paths = "/System/Library/Fonts/Supplemental",
  prompt = FALSE,
  pattern = "^Arial Narrow"
  )
loadfonts(device = "postscript", quiet = TRUE)

```


```{r get_data}
source("get data function.R")
data <- get.data("Nation")
data <- data[1:(nrow(data)-15),]
```

```{r}
library(ggplot2)
Sys.setlocale("LC_TIME","English")
data.plot.each <- function(type, data.import) {
  if (type %in% c("Protest", "Lockdown", "schools_universities")) {
    data.import[[type]] <-
      data.import[[type]]/max(data.import[[type]])*20000
  }
  data.value <- as.data.frame(
    cbind(
      as.character(data.import$date), 
      data.import[,type], 
      rep(type, nrow(data.import), stringsAsFactors=FALSE)
      ), stringsAsFactors = FALSE
  )
  colnames(data.value) <- c("date", "value", "type")
  return(data.value)
}
data.plot <- as.data.frame(
  rbind(
    data.plot.each("cases", data),
    data.plot.each("deaths", data),
    data.plot.each("Beds", data), stringsAsFactors=FALSE
  ), stringsAsFactors = FALSE
)
data.plot$date <- as.Date(data.plot$date)
data.plot$value <- as.numeric(data.plot$value)
  
ggplot(
  data.plot, 
  aes(x = date, y = value, colour = type)) +
  geom_line() +
  scale_x_date(date_breaks="6 week",date_labels="%d %b %y") +
  theme_bw() +
  theme(
    panel.border = element_blank(),
    axis.text.x= element_text(size = 11, angle=45, hjust=1)
    )
```

```{r}
time.start <- as.Date("2020-02-01")
time.end <- as.Date("2020-10-01")
data <- filter(data, date < time.end)
data <- filter(data, date > time.start)



data.plot.01 <- rbind(
  data.plot.each("Protest", data),
  data.plot.each("Lockdown", data),
  data.plot.each("schools_universities", data)
)
data.plot.01$value <- as.numeric(data.plot.01$value)
data.plot.01$line <- "NPI"
data.plot <- rbind(
  data.plot.each("cases", data),
  data.plot.each("deaths", data),
  data.plot.each("inhospital", data),
  data.plot.each("Beds", data)
)
data.plot$value <- as.numeric(data.plot$value)
data.plot$line <- "Observations"
data.plot.all <- rbind(data.plot.01, data.plot)
data.plot.all$date <- as.Date(data.plot.all$date)
ggplot(
  data.plot.all, 
  aes(x = date, y = value, colour = type, linetype = line)) +
  geom_line() +
  scale_x_date(date_breaks="3 week",date_labels="%d %b") +
  scale_y_continuous(
    sec.axis = sec_axis(
      ~ ./20000,
      name = "Index")
    ) +
  scale_linetype_manual(values = c('longdash', 'solid'))+
  theme_bw() +
  theme(
    panel.border = element_blank(),
    axis.text.x= element_text(size = 11, angle=45, hjust=1)
    )

```

```{r model_set_up}
library(epidemia)
plot.cases <- function(
  start , end, method = c("deaths", "Beds"), data) {
  data <- data[data$date < as.Date(end),]
  row.names(data) <- 1:nrow(data)
  data <- data[data$date > as.Date(start),]
  data$inhospital <- log(data$inhospital + 1)
  data$inhospital <- (
    data$inhospital- 
      min(data$inhospital, na.rm = TRUE))/(
        max(data$inhospital, na.rm = TRUE) - 
          min(data$inhospital, na.rm = TRUE))
  data$I <- data$LRI - data$LRE
  # reproduction number
  rt <- epirt(
   formula = R(Nation, date) ~ 1 + Protest +
     schools_universities +  Lockdown,
    prior = shifted_gamma(
      shape=2, scale = 1/3, shift = log(1.05)/6
    ),
    prior_covariance = decov(
      shape = c(2, rep(0.5, 5)),scale=0.25
    ),
    prior_intercept = rstanarm::normal(0.5,1),
    link = scaled_logit(5.7)
  )
  # the infection model 
  inf <- epiinf(
    gen = EuropeCovid2$si, 
    seed_days = 5
  )
  if (method == "deaths") {
    observation <- epiobs(
        formula = deaths ~ 1,
        i2o = EuropeCovid2$inf2death, 
        prior_intercept = normal(0, 1),
        link = scaled_logit(0.02)
    )
  } else if (method == "Beds") {
    observation <- epiobs(
        formula = Beds ~ 1 + inhospital,
        i2o = dlnorm(1:20, 1.921, 0.428),   #https://www.acpjournals.org/doi/full/10.7326/M20-0504
        link = scaled_logit(0.276),
        prior_intercept = normal(0, 0.5),
        center = TRUE
    )
  } else if (method == "deaths_inacurate") {
      observation <- epiobs(
        formula = deaths ~ 1 + inhospital,
        i2o = EuropeCovid2$inf2death, 
        prior_intercept = normal(0, 1),
        link = scaled_logit(0.02)
        )
      method <- "deaths"
  }
  args <- list(
    rt=rt, inf=inf, obs=observation, 
    data=data, seed=12345, refresh=0
  )
  options(mc.cores = parallel::detectCores())
  pr_args <- c(
    args, 
    list(
      algorithm="sampling", iter=1e4, 
      prior_PD=TRUE, control = list(adapt_delta = 0.99)
      )
    )
  fm_prior <- do.call(epim, pr_args)
  p1 <- plot_rt(fm_prior, levels = c(30, 60, 95))
  args$algorithm <- "fullrank"
  args$iter <- 50000
  args$tol_rel_obj <- 1e-8
  fm <- do.call(epim, args)
  p2 <- plot_rt(
    fm, step = T, levels = c(30, 60, 95)
    )
  p3 <- plot_obs(
    fm, type = method, step = T, levels = c(30, 60, 95)
    )
  p4 <- plot_infections(
    fm, levels = c(30, 60, 95), step = T
    )
  p5 <- plot_infections(
    fm, levels = c(30, 60, 95), step = T, 
    cumulative = TRUE
    )
  return(list(prior = p1, rt = p2, obs = p3, infection = p4, cum = p5))
}
```


```{r imputation}
data.bed <- data
data.bed$index <- 1:nrow(data)
data.bed$index2 <- data.bed$index^2
data.impute <- filter(data.bed, date < as.Date("2020-05-09"))
data.impute <- filter(data.impute, date > as.Date("2020-04-01"))
reg <- lm(Beds ~ index + index2, data.impute)
sigma <- sd(reg$residuals)
coef <- reg$coefficients
for (i in 1:nrow(data.bed)) {
  set.seed <- 1234
  b <- round(
    as.numeric(coef[1]) + as.numeric(coef[2]) * data.bed$index[i]
    + as.numeric(coef[3]) * data.bed$index2[i] + rnorm(1, 0, sigma)
    )
  if (b > 0){
    data.bed$Beds[i] <- b
  }
  if (data.bed$date[i] >= as.Date("2020-04-02")) {
    break
  }
}

data.impute <- filter(data.bed, date < as.Date("2020-04-14"))
data.impute <- filter(data.impute, date > as.Date("2020-03-26"))
reg <- lm(inhospital ~ index , data.impute)
sigma <- sd(reg$residuals)
coef <- reg$coefficients
for (i in 1:nrow(data.bed)) {
  set.seed <- 1234
  b <- round(
    as.numeric(coef[1]) + as.numeric(coef[2]) * data.bed$index[i]
    + rnorm(1, 0, sigma/5)
    )
  if (b > 0){
    data.bed$inhospital[i] <- b
  }
  if (data.bed$date[i] > as.Date("2020-03-26")) {
    break
  }
}
```

```{r fitness}

p.death <- plot.cases(
  start = time.start, end = time.end, 
  method = "deaths", data = data
  )
p.beds <- plot.cases(
  start = time.start, end = time.end, 
  method = "Beds", data = data.bed
  )
p.death.in <- plot.cases(
  start = time.start, end = time.end, 
  method = "deaths_inacurate", data = data.bed
  )
```

```{r add_react_prior}
add.react <- function(plot) {
  data.rt <- read.csv("./data/Rt.csv")
  data.rt$date <- as.Date(data.rt$date)
  plot <- plot + 
    geom_rect(
      aes(
        xmin=as.Date('2020-05-01'), 
        xmax=as.Date('2020-06-01'), 
        ymin=0.445, ymax=0.725),
      fill='#00BFFF',alpha = 0.015) +
    geom_rect(
      aes(
        xmin=as.Date('2020-05-01'), 
        xmax=as.Date('2020-06-01'), 
        ymin=0.555, ymax=0.575),
      fill='#000080',alpha = 0.9) +
    geom_rect(
      aes(
        xmin=as.Date('2020-06-01'), 
        xmax=as.Date('2020-07-01'), 
        ymin=0.815, ymax=0.975),
      fill='#00BFFF',alpha = 0.015) +
    geom_rect(
      aes(
        xmin=as.Date('2020-06-01'), 
        xmax=as.Date('2020-07-01'), 
        ymin=0.88, ymax=0.9),
      fill='#000080',alpha = 0.9) +
    geom_rect(
      aes(
        xmin=as.Date('2020-07-24'), 
        xmax=as.Date('2020-08-11'), 
        ymin=1.2, ymax=1.4),
      fill='#00BFFF',alpha = 0.015) +
    geom_rect(
      aes(
        xmin=as.Date('2020-07-24'), 
        xmax=as.Date('2020-08-11'), 
        ymin=1.29, ymax=1.31),
      fill='#000080',alpha = 0.9) +  
    geom_rect(
      aes(
        xmin=as.Date('2020-08-22'), 
        xmax=as.Date('2020-09-07'), 
        ymin=1.4, ymax=2.0),
      fill='#00BFFF',alpha = 0.015) +
    geom_rect(
      aes(
        xmin=as.Date('2020-08-22'), 
        xmax=as.Date('2020-09-07'), 
        ymin=1.69, ymax=1.71),
      fill='#000080',alpha = 0.9) +  
    geom_rect(
      aes(
        xmin=as.Date('2020-09-18'), 
        xmax=as.Date('2020-09-26'), 
        ymin=0.7, ymax=1.5),
      alpha = 0.015,fill='#00BFFF') +
    geom_rect(
      aes(
        xmin=as.Date('2020-09-18'), 
        xmax=as.Date('2020-09-26'), 
        ymin=1.05, ymax=1.07),
      fill='#000080',alpha = 0.9) +
    geom_ribbon(
      aes(ymin=min, ymax=max, x=date), data = data.rt,
    alpha = 0.3, fill = "#FF0000")
  return(plot)
}

```

```{r , fig.cap="Prior reproduction number until Oct 1st, 2020", fig.align='center'}
add.react(p.death$prior)
```


```{r}
data.bed <- data.bed[data.bed$date < as.Date(time.end),]
row.names(data.bed) <- 1:nrow(data.bed)
data.bed <- data.bed[data.bed$date > as.Date(time.start),]
new.data.case <- data.bed[,c("date", "cases")]
new.data.case$type <- "Case"
colnames(new.data.case) <- c("date", "num", "type")
new.data.bed <- data.bed[,c("date", "Beds")]
new.data.bed$type <- "Ventilated Bed (Observed)"
new.data.bed$type[1:61] <- "Ventilated Bed (Imputation)"
colnames(new.data.bed) <- c("date", "num", "type")
new.data.hos <- data.bed[,c("date", "inhospital")]
new.data.hos$type <- "In hospital (Observed)"
new.data.hos$type[1:54] <- "In hospital (Imputation)"
colnames(new.data.hos) <- c("date", "num", "type")
new.data.death <- data.bed[,c("date", "deaths")]
new.data.death$type <- "Death"
colnames(new.data.death) <- c("date", "num", "type")
new.data <- rbind(
  new.data.case[-nrow(new.data.case),],
  new.data.bed[-nrow(new.data.bed),],
  new.data.death[-nrow(new.data.death),],
  new.data.hos[-nrow(new.data.hos),]
  )
```

```{r fig.cap="Simulation infection from daily death data until Oct 1st, 2020", fig.align='center'}
new.data.temp <- rbind(
  filter(new.data, type == "Death"), 
  filter(new.data, type == "Case")
)
p.death$infection + geom_line(
  aes(x = date, y = num*8, colour = type), 
  lwd = 1, data = new.data.temp) +
  scale_y_continuous(
    sec.axis = sec_axis(~ ./8, 
    name = "Observed")) +
  theme(legend.position = "right")
```

```{r fig.cap="Simulation infection from daily on the Beds data until Oct 1st, 2020", fig.align='center'}
new.data.temp <- filter(new.data, type != "Death")
p.beds$infection + geom_line(
  aes(x = date, y = num*4, fill = type), 
  lwd = 1, data = new.data.temp) +
  scale_y_continuous(
    sec.axis = sec_axis(~ ./4, name = "Observed")
    ) +
  theme(legend.position = "right")
```

```{r , fig.cap="Simulation reproduction number from death data until Oct 1st, 2020", fig.align='center'}
add.react(p.death$rt)
```

```{r reproduction_number, fig.cap="Simulation reproduction number from Ventilated beds data until Oct 1st, 2020", fig.align='center'}
add.react(p.beds$rt)
```

```{r observation, fig.cap="Fitness of obeservation from death data until Oct 1st, 2020", fig.align='center'}
p.death$obs
```

```{r , fig.cap="Fitness of obeservation from Ventilated beds data until Oct 1st, 2020", fig.align='center'}
data.bed.obs <- p.beds$obs$data
data.bed.obs$obs <- "Observation"
data.bed.obs$obs[49:61] <- "Imputation"
data.bed <- filter(data.bed, date < as.Date("2020-10-01"))
data.bed <- filter(data.bed, date > as.Date("2020-02-01"))
data.temp <- filter(data.bed.obs, level == "30")
data.temp6 <- filter(data.bed.obs, level == "60")
data.temp9 <- filter(data.bed.obs, level == "95")
data.temp$simu <- 0.5*(data.temp$lower + data.temp$upper)
data.temp$Beds <- data.bed$Beds

p.beds$obs <- ggplot() + 
  geom_line(
    aes(date, simu), data = data.temp, 
    lwd = 1, colour = "#102631") +
  geom_bar(
    aes(x = date, y = Beds, fill = obs), data = data.temp,
    stat="identity") +
  scale_x_date(date_breaks="3 week",date_labels="%d %b") +
    scale_fill_manual(
    values=c("#006400","#8B3E2F")) + 
  scale_y_continuous(" ") +
  geom_ribbon(
    aes(ymin=lower, ymax=upper, x=date), data = data.temp,
    alpha = 0.6, fill = "#236585") + 
  geom_ribbon(
    aes(ymin=lower, ymax=upper, x=date), data = data.temp6,
    alpha = 0.4, fill = "#1A7796") + 
  geom_line(
    aes(x = date, y = num, colour = type), 
    data = new.data.hos, lwd = 1
  ) +
  scale_color_manual(values=c('#FFA500','#00FA9A')) +
  geom_ribbon(
    aes(ymin=lower, ymax=upper, x=date), data = data.temp9,
    alpha = 0.2, fill = "#447D99") + 
  theme_bw() + guides(fill=F) + 
  theme(
    panel.border = element_blank(),
    plot.margin=unit(c(2,2,1,1.5), 'lines',),
    axis.text.x= element_text(size = 11, angle=45, hjust=1),
    legend.position = "top"
    )
p.beds$obs <- p.beds$obs + theme(axis.title.x=element_blank())
p.beds$obs
```

```{r cumulative}
pop <- 66519604
add.cum <- function(p) {
  p <- p +
  annotate( # REACT
    x = as.Date("2020-07-15"), xend = as.Date("2020-07-15"), 
    y = 3.695*10^6, yend = 3.886*10^6, 
    geom = "segment", size = 0.8, colour = "red") +
  annotate(
    x = as.Date("2020-07-13"), xend = as.Date("2020-07-17"), 
    y = 3.695*10^6, yend = 3.695*10^6, 
    geom = "segment", size = 0.8, colour = "red") +
  annotate(
    x = as.Date("2020-07-13"), xend = as.Date("2020-07-17"), 
    y = 3.886*10^6, yend = 3.886*10^6, 
    geom = "segment", size = 0.8, colour = "red") +
  geom_point(mapping = aes(
    x = as.Date("2020-07-15"), y = 3.822*10^6), 
    size = 2.5, shape = 18, colour = "red") +
  annotate( # ONS
    x = as.Date("2020-04-26"), xend = as.Date("2020-06-02"), 
    y = 0.0521*pop, yend = 0.0521*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  annotate(
    x = as.Date("2020-04-26"), xend = as.Date("2020-06-02"), 
    y = 0.0864*pop, yend = 0.0864*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  annotate(
    x = as.Date("2020-05-14"), xend = as.Date("2020-05-14"), 
    y = 0.0521*pop, yend = 0.0864*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  geom_point(mapping = aes(
    x = as.Date("2020-05-14"), y = 0.0678*pop), 
    size = 5, shape = 18, colour = "yellow") +
  annotate(
    x = as.Date("2020-06-03"), xend = as.Date("2020-06-18"), 
    y = 0.043*pop, yend = 0.043*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  annotate(
    x = as.Date("2020-06-03"), xend = as.Date("2020-06-18"), 
    y = 0.065*pop, yend = 0.065*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  annotate(
    x = as.Date("2020-06-11"), xend = as.Date("2020-06-11"), 
    y = 0.043*pop, yend = 0.065*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  geom_point(mapping = aes(
    x = as.Date("2020-06-11"), y = 0.054*pop), 
    size = 5, shape = 18, colour = "yellow") +
  annotate(
    x = as.Date("2020-06-19"), xend = as.Date("2020-07-02"), 
    y = 0.047*pop, yend = 0.047*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  annotate(
    x = as.Date("2020-06-19"), xend = as.Date("2020-07-02"), 
    y = 0.081*pop, yend = 0.081*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  annotate(
    x = as.Date("2020-06-26"), xend = as.Date("2020-06-26"), 
    y = 0.047*pop, yend = 0.081*pop, 
    geom = "segment", size = 0.8, colour = "yellow") +
  geom_point(mapping = aes(
    x = as.Date("2020-06-26"), y = 0.063*pop), 
    size = 5, colour = "yellow", shape = 18) +
  annotate( # Oxford
    x = as.Date("2020-04-14"), xend = as.Date("2020-06-15"), 
    y = 0.04*pop, yend = 0.04*pop, 
    geom = "segment", size = 0.8, colour = "purple") +
  annotate(
    x = as.Date("2020-04-14"), xend = as.Date("2020-06-15"), 
    y = 0.069*pop, yend = 0.069*pop, 
    geom = "segment", size = 0.8, colour = "purple") +
  annotate(
    x = as.Date("2020-05-15"), xend = as.Date("2020-05-15"), 
    y = 0.04*pop, yend = 0.069*pop, 
    geom = "segment", size = 0.8, colour = "purple") +
  geom_point(mapping = aes( 
    x = as.Date("2020-05-15"), y = 0.053*pop), 
    size = 5, colour = "purple", shape = 18) +
  annotate( # Greater Glasgow region
    x = as.Date("2020-04-18"), xend = as.Date("2020-04-20"), 
    y = 0.06095*pop, yend = 0.06095*pop, 
    geom = "segment", size = 0.8, colour = "green") +
  annotate(
    x = as.Date("2020-04-18"), xend = as.Date("2020-04-20"), 
    y = 0.11047*pop, yend = 0.11047*pop, 
    geom = "segment", size = 0.8, colour = "green") +
  annotate(
    x = as.Date("2020-04-19"), xend = as.Date("2020-04-19"), 
    y = 0.06095*pop, yend = 0.11047*pop, 
    geom = "segment", size = 0.8, colour = "green") +
  geom_point(mapping = aes(
    x = as.Date("2020-04-19"), y = 42/490*pop), 
    size = 5, colour = "green", shape = 18)
  return(p)
}
```

```{r , fig.cap="Cumulative simulated cases from death data until Oct 1st, 2020", fig.align='center'}
add.cum(p.death$cum)
```

```{r , fig.cap="Cumulative simulated cases from Ventilated beds data until Oct 1st, 2020", fig.align='center'}
add.cum(p.beds$cum)
```

```{r , fig.cap="Sampling Procentage of Simulation from Ventilated beds data until Oct 1st, 2020", fig.align='center'}
trans.sampling <- function(infection, data){
  median <- infection$layers[[2]]$data
  median$median <- data$cases / median$median * 100 + 0.01
  infection.data <- infection$data
  infection.data.30 <- filter(
    infection.data, level == "30"
  )
  infection.data.30$lower <- 
    data$cases / infection.data.30$lower * 100 + 0.01
  infection.data.30$upper <- 
    data$cases / infection.data.30$upper * 100 + 0.01
  infection.data.60 <- filter(
    infection.data, level == "60"
  )
  infection.data.60$lower <- 
    data$cases / infection.data.60$lower * 100 + 0.01
  infection.data.60$upper <- 
    data$cases / infection.data.60$upper * 100 + 0.01
  infection.data.95 <- filter(
    infection.data, level == "95"
  )
  infection.data.95$lower <- 
    data$cases / infection.data.95$lower * 100 + 0.01
  infection.data.95$upper <- 
    data$cases / infection.data.95$upper * 100 + 0.01

  sampling <- ggplot() + 
    geom_line(
      aes(date, median), data = median, 
      lwd = 1, colour = "#102631") +
    geom_ribbon(
      aes(ymin=upper, ymax=lower, x=date), 
      data = infection.data.30,
      alpha = 0.6, fill = "#236585") + 
    geom_ribbon(
      aes(ymin=upper, ymax=lower, x=date), 
      data = infection.data.60,
      alpha = 0.4, fill = "#1A7796") + 
    geom_ribbon(
      aes(ymin=upper, ymax=lower, x=date), 
      data = infection.data.95,
      alpha = 0.2, fill = "#447D99") + 
    geom_hline(
      aes(yintercept=100), 
      colour="#990000", linetype="dashed") +
    scale_x_date(date_breaks="3 week",date_labels="%d %b") +
    scale_y_log10(
      "Sampling Precentage (%)",
      labels = scales :: comma) +
    theme_bw() + guides(fill=F) + 
    theme(
      panel.border = element_blank(),
      plot.margin=unit(c(2,2,1,1.5), 'lines',),
      axis.text.x= element_text(size = 11, angle=45, hjust=1),
      legend.position = "top",
      axis.title.x=element_blank()
      )
  return(sampling)
}

trans.sampling(p.beds$infection, data)
```

```{r , fig.cap="Sampling Procentage of Simulation from death data until Oct 1st, 2020", fig.align='center'}
trans.sampling(p.death$infection, data)
```


```{r}
p.death.in$rt <- add.react(p.death.in$rt)

new.data.infection <- rbind(
  new.data.case,
  new.data.death,
  new.data.hos
)
p.death.in$infection <- p.death.in$infection + geom_line(
  aes(x = date, y = num*4, fill = type), 
  lwd = 1, data = new.data.infection) +
  scale_y_continuous(
    sec.axis = sec_axis(~ ./4, 
    name = "Observed")) +
  theme(legend.position = "right")

p.death.in$cum <- add.cum(p.death.in$cum)

p.death.in$obs <- p.death.in$obs + 
  geom_bar(
    aes(x = date, y = num, fill = type),
    data = new.data.hos, stat = "identity"
    )
```



```{r, fig.align='center'}
cowplot::plot_grid(
  p.death.in$rt, p.death.in$obs,
  p.death.in$infection, p.death.in$cum,
  nrow = 2, ncol = 2
)
```


```{r, fig.align='center'}
trans.sampling(p.death.in$infection, data)
```