---
title: "moltiple"
output: html_document
---
```{r global_options, echo=FALSE, message=FALSE, warning=FALSE,include=FALSE, results='hide'}
knitr::opts_chunk$set(
  fig.width=8, fig.height=5,
  echo=FALSE, warning=FALSE, message=FALSE
  )
```

```{r}
options (warn = -1)
rm(list = ls())
library(dplyr)
library(epidemia)
library(rstanarm)
library(httr)
library(jsonlite)
library(Hmisc)
library(knitr)
library(lubridate)
library(ggplot2)
library(tidyverse)
extrafont::loadfonts()

setwd("/Users/wanghanlin/Desktop/final project")
temperature <- read.csv("temperature.csv")
protest <- read.csv("protest.csv")
protest$week <- as.Date(protest$week)

temperature$date <- as.Date(temperature$date)
temp <- seq.Date(from = as.Date("2020/01/05",format = "%Y/%m/%d"), by = "day", length.out = as.numeric(difftime("2021-06-06", "2020-01-05")))
protest.new <- data.frame(date <- temp)
colnames(protest.new) <- c("date")
protest.new$protest <- -1
for (i in row.names(protest.new)) {
  date <- as.Date(protest.new$date[as.numeric(i)])
  for (j in row.names(protest)) {
    if (date == as.Date(protest$week[as.numeric(j)])) {
      protest.new[i, "protest"] <- protest$protest[as.numeric(j)]
      break
    } else {
      protest.new[i, "protest"] <- NA
    }
  }
}
protest <- protest.new
rm(protest.new)
for (i in row.names(protest)) {
  i <- as.numeric(i)
  date <- protest$date[i]
  if (is.na(protest$protest[i])) {
    posterior.date <- protest$date[nrow(protest)]
    posterior.protest <- former.protest
    for (j in (i+1: nrow(protest))) {
      if (is.na(protest$protest[j]) == FALSE) {
        posterior.date <- protest$date[j]
        posterior.protest <- protest$protest[j]
        break
      }
    }
    former.diff.day <- abs(as.numeric(difftime(former.date, date)))
    posterior.diff.day <- abs(as.numeric(difftime(posterior.date, date)))
    protest[i, "protest"] <- (
      former.protest * posterior.diff.day
      + posterior.protest * former.diff.day
      )/(former.diff.day + posterior.diff.day)
  } else {
    former.date <- date
    former.protest <- protest$protest[i]
  }
}

download.data <- function() {
  # API request
  AREA_TYPE = "overview"

  endpoint <- "https://coronavirus.data.gov.uk/api/v1/data"

  # Create filters:
  filters <- c(
    sprintf("areaType=%s", AREA_TYPE)
  )

  # Create the structure as a list or a list of lists:
  structure <- list(
      region = "areaName",
      date = "date", 
      cases = "newCasesByPublishDate",
      cumulativeCases = "cumCasesByPublishDate",
      deaths = "newDeaths28DaysByDeathDate", 
      cumulativeDeaths = "cumDeaths28DaysByPublishDate",
      # cumDailyNsoDeathsByDeathDate
      # Patients in hospital
      hospital = "hospitalCases",
      ventilationbeds = "covidOccupiedMVBeds",
      newfirstVaccination = "newPeopleVaccinatedFirstDoseByPublishDate",
      cumfirstVaccination = "cumPeopleVaccinatedFirstDoseByPublishDate",
      newsecondVaccination = "newPeopleVaccinatedSecondDoseByPublishDate",
      cumsecondVaccination = "cumPeopleVaccinatedSecondDoseByPublishDate"
  )

  response <- GET(
    url = endpoint,
    query = list(
          filters = paste(filters, collapse = ";"),
          structure = jsonlite::toJSON(structure, auto_unbox = TRUE)
      ),
    content_type("application/json"),
    timeout(10)
  ) 

  # Handle errors:
  if (response$status_code >= 400) {
      err_msg = httr::http_status(response)
      stop(err_msg)
  }

  # Convert response from binary to JSON:
  json_text <- content(response, "text")
  data      <- fromJSON(json_text)$data
  data$pop <- pop <-  56286961
  data$date <- as.Date(data$date)
  rownames(data) <- data$date
  for (d in row.names(data)) {
    differ = as.numeric(difftime(d, '2020-12-8'))
    if (differ < 0) {
      data[
        d, c(
          "newfirstVaccination", "cumfirstVaccination",
          "newsecondVaccination", "cumsecondVaccination"
          )] <- c(0,0,0,0)
    }
  }
  for (d in row.names(data)) {
    if (is.na(data[d, "cumfirstVaccination"])) {
      differ.all = as.numeric(difftime('2021-01-10', '2020-12-7'))
      differ = as.numeric(difftime(d, '2020-12-7'))
      cum <- data['2021-01-10', "cumfirstVaccination"] / differ.all
      data[d, "cumfirstVaccination"] <- round(cum * differ)
    }
  }
  for (d in row.names(data)) {
    if (is.na(data[d, "newfirstVaccination"])) {
      cum <- data[d, "cumfirstVaccination"]
      x <- ymd(d)
      day(x) <- day(d) - 1
      x <- as.character(x)
      data[d, "newfirstVaccination"] <- cum - data[x, "cumfirstVaccination"]
    }
  }
  for (d in row.names(data)) {
    if (is.na(data[d, "cumsecondVaccination"])) {
      if (difftime(d, '2021-01-04') > 0) {
        differ.all = as.numeric(difftime('2021-01-10', '2021-01-04'))
        differ = as.numeric(difftime(d, '2021-01-04'))
        cum <- data['2021-01-10', "cumsecondVaccination"] / differ.all
        data[d, "cumsecondVaccination"] <- round(cum * differ)
      } else {
        data[d, "cumsecondVaccination"] <- 0
      }
    }
  }
  for (d in row.names(data)) {
    if (is.na(data[d, "newsecondVaccination"])) {
      cum <- data[d, "cumsecondVaccination"]
      x <- ymd(d)
      day(x) <- day(d) - 1
      x <- as.character(x)
      data[
        d, "newsecondVaccination"
        ] <- cum - data[x, "cumsecondVaccination"]
    }
  }
  data$FirstVaccinationRate = data$cumfirstVaccination / data$pop
  data$SecondVaccinationRate = data$cumsecondVaccination / data$pop

  for (d in row.names(data)) {
    if (as.numeric(difftime(d, '2020-03-11')) > 0) {
      data[d,"self_isolating_if_ill"] <- 1
      if (as.numeric(difftime(d, '2020-03-15')) > 0) {
        data[d,"social_distancing_encouraged"] <- 1
        if (as.numeric(difftime(d, '2021-03-28')) > 0) {
          data[d,"social_distancing_encouraged"] <- 0.2
        }
        if (as.numeric(difftime(d, '2020-03-20')) > 0) {
          data[d,"schools_universities"] <- 1
          if (as.numeric(difftime(d, '2020-09-20')) > 0) {
            data[d,"schools_universities"] <- 0.7
            if (as.numeric(difftime(d, '2021-03-07')) > 0) {
              data[d,"schools_universities"] <- 0.3
            }
          }
          if (as.numeric(difftime(d, '2020-03-23')) > 0) {
            data[d,"public_events"] <- 1
            if (as.numeric(difftime(d, '2021-05-16')) > 0) {
              data[d,"public_events"] <- 0.5
            }
            data[d,"lockdown"] <- 1
          } 
        } 
      } 
    } 
  }
  
  for (d in row.names(data)) {
    d <- ymd(d)
    M <- month(d)
    Y <- year(d)
    for (i in row.names(temperature)) {
      tem <- ymd(temperature$date[as.numeric(i)])
      if (Y == year(tem)) {
        if (M == month(tem))
          data[as.character(d), 'temperature'] <- temperature$temperature[as.numeric(i)]
      }
    }
  }
  
  new.index <- function(date) {
    return(round(as.numeric(difftime(date, "2020-01-30"))))
  }
  data$index = as.numeric(lapply(data$date, new.index))
  data <- data[order(data$index),]
  row.names(data) <- data$index
  data_new <- data[,c(
    "region", "date", "cases", "deaths", "schools_universities",
    "self_isolating_if_ill", "public_events" ,"lockdown",
    "social_distancing_encouraged", "FirstVaccinationRate",
    "SecondVaccinationRate", "temperature", "pop"
    )]

  for (c in colnames(data_new)) {
    for (r in row.names(data_new)) {
      if (is.na(data_new[r,c])) {
        data_new[r,c] <- 0
      }
    }
  }
  data <- data_new
  row.names(protest) <- protest$date
  for (i in row.names(data)) {
    date <- as.character(data$date[as.numeric(i)])
    data[i, "protest"] <- as.numeric(protest[date, "protest"])
  }

  return(data)
}
data <- download.data()

data <- filter(data, date < as.Date("2021-06-04"))
data <- filter(data, date > max(date) - 80)
data$cases[1:20] <- NA

```
```{r}
data <- data %>% mutate(dt = replace(date, date < as.Date("2020-04-01"), NA))
```

```{r}
data$pop <- pop <-  56286961
rt <- epirt(formula = R(region, date) ~ 1 + rw(time = dt, prior_scale=0.05),
            link = scaled_logit(7), prior_intercept = normal(-1,1))
inf <- epiinf(
  gen = EuropeCovid$si, seed_days=20L, pop_adjust = TRUE, 
  pops = pop, prior_susc = normal(0.49, 0.1), 
  prior_seeds = normal(15e3, 2e3)
  )
data$day <- wday(data$date, label=T)
cases <- epiobs(formula = cases ~ 1 + factor(day, ordered = FALSE) +
                  rw(time = dt, prior_scale = 0.05),
                i2o =  c(rep(0,3), rep(1/7,7)), link = "logit",
                prior_intercept = normal(0,1.5), prior = normal(0,0.5),
                family = "quasi_poisson", prior_aux = normal(10,5))
ons <- data.frame(date = as.Date("2021-04-01") + 7 * (0:6),
                  positivity = c(0.21, 0.17, 0.1, 0.08, 0.07, 0.09, 0.09))
data <- left_join(data, ons)
data$off <- 1
ons <- epiobs(
  formula = positivity ~ 0 + offset(off),
  i2o = c(rep(0,3), rep(1,14)) * 100 / pop, 
  link = "identity", family = "normal", 
  prior_aux = normal(0.01, 2.5e-3)
  )
fm <- epim(
  rt = rt, inf = inf, obs = list(cases, ons), 
  data = data, iter = 4e3, 
  control = list(max_treedepth = 12), seed=12345
  )
```

